[package]
name = "dynastes"
version = "0.1.0"
edition = "2021"
authors = ["Juniper Parsons"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lib]
crate-type = ["rlib"]
edition = "2021"
